import { Users, Building2, GraduationCap, Briefcase } from "lucide-react";

export const servicesData = [
  {
    slug: "personal-tax",
    title: "Personal Tax",
    icon: Users,
    description: "Expert personal tax preparation for individuals, families, and seniors.",
    longDescription: "Our personal tax services cover everything from simple T4 returns to complex investment income, rental properties, and capital gains. We ensure you claim all eligible deductions and credits to maximize your refund.",
    whoIsItFor: "Individuals, families, seniors, and anyone with personal income to report.",
    documents: [
      "T4 slips (employment income)",
      "T5 slips (investment income)",
      "Rental property income and expenses",
      "Medical receipts",
      "Charitable donation receipts",
      "RRSP contribution receipts",
      "Tuition receipts (T2202)",
    ],
    benefits: [
      "Maximize refund with all eligible credits",
      "Expert handling of capital gains/losses",
      "Rental property income optimization",
      "Tax planning for future years",
    ],
    ctaText: "Book Your Personal Tax Appointment",
    ctaLink: "/contact",
  },
  {
    slug: "corporate-tax",
    title: "Corporate Tax",
    icon: Building2,
    description: "Comprehensive corporate tax services for businesses of all sizes.",
    longDescription: "We help corporations navigate the complexities of corporate tax returns, GST/HST, payroll, and more. Our services ensure compliance while minimizing tax liability.",
    whoIsItFor: "Corporations, small to large businesses, startups, and non-profits.",
    documents: [
      "Financial statements (balance sheet, income statement)",
      "General ledger",
      "T4 summary and payroll records",
      "GST/HST returns",
      "Capital asset purchases",
      "Shareholder information",
    ],
    benefits: [
      "Accurate corporate tax filing (T2)",
      "GST/HST and payroll registration & filing",
      "Tax planning and advice",
      "Incorporation services",
    ],
    ctaText: "Discuss Your Corporate Tax Needs",
    ctaLink: "/contact",
  },
  {
    slug: "international-students",
    title: "International Students",
    icon: GraduationCap,
    description: "Tax filing and advice tailored for international students.",
    longDescription: "International students often qualify for tax refunds and credits they don't know about. We guide you through the process and help you get the most out of your tax return.",
    whoIsItFor: "International students studying in Canada.",
    documents: [
      "T2202 tuition tax certificate",
      "T4A (scholarships, bursaries)",
      "T4 (if employed)",
      "Rent receipts (for Ontario Trillium Benefit)",
      "Bank account details for direct deposit",
    ],
    benefits: [
      "Claim tuition credits",
      "Get GST/HST credit refunds",
      "Understand your residency status",
      "File previous years' returns",
    ],
    ctaText: "Get Your Student Tax Refund",
    ctaLink: "/contact",
  },
  {
    slug: "small-business",
    title: "Small Business",
    icon: Briefcase,
    description: "Tax and accounting solutions for self-employed individuals and small businesses.",
    longDescription: "Whether you're a freelancer, consultant, or small business owner, we help you manage your taxes, track expenses, and plan for growth.",
    whoIsItFor: "Sole proprietors, partnerships, freelancers, and small business owners.",
    documents: [
      "T2125 statement of business activities",
      "Income and expense records",
      "Vehicle and home office expenses",
      "GST/HST records",
      "Bank statements",
    ],
    benefits: [
      "Maximize business expense deductions",
      "GST/HST filing and advice",
      "Bookkeeping support",
      "Business structure guidance",
    ],
    ctaText: "Grow Your Business with Smart Tax Planning",
    ctaLink: "/contact",
  },
];